POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{ customer(id: 1) { id name age accounts { id accountType balance } } }"
}

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation {addCustomer(name: \"John\", age: 18) {id name age}}"
}

###

